name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flutter-version: [3.24.3]
        channel: [stable]

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: ${{ matrix.channel }}

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # # 4. Run tests
      # - name: Run tests
      #   run: flutter test --no-pub --coverage

      # 5. Build APK (for Android)
      - name: Build APK
        run: flutter build apk --release

      # 6. Build IPA (for iOS)
      - name: Build IPA
        if: runner.os == 'macOS'
        run: flutter build ios --release

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: latest
          channel: stable

      # # 3. Deploy APK to Firebase App Distribution (for Android)
      # - name: Deploy APK to Firebase App Distribution
      #   if: always()
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
      #     token: ${{ secrets.FIREBASE_TOKEN }}
      #     groups: testers
      #     file: build/app/outputs/flutter-apk/app-release.apk

      # # 4. Deploy IPA to Firebase App Distribution (for iOS)
      # - name: Deploy IPA to Firebase App Distribution
      #   if: runner.os == 'macOS'
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{ secrets.FIREBASE_APP_ID_IOS }}
      #     token: ${{ secrets.FIREBASE_TOKEN }}
      #     groups: testers
      #     file: build/ios/ipa/app.ipa
